package org.iqmanager.models.enum_models;

public enum Languages {
    ar,// "العربية"
    az,// "Azərbaycanca / آذربايجان ",
    be,// "Беларуская",
    bg,// "Български",
    da,// "Dansk",
    de,// "Deutsch",
    el,// "Ελληνικά",
    en,// "English",
    et,// "Eesti",
    fi,// "Suomi",
    fr,// "Français",
    ga,// "Gaeilge",
    hr,// "Hrvatski",
    hu,// "Magyar",
    hy,// "Հայերեն",
    it,// "Italiano",
    ja,// "日本語",
    kk,// "Қазақша",
    ky,// "Kırgızca / Кыргызча",
    lv,// "Latviešu",
    mo,// "Moldovenească",
    mt,// "bil-Malti",
    nl,// "Dutch",
    pl,// "Polski",
    pt,// "Português",
    ro,// "Română",
    ru,// "Русский",
    sc,// "Česky",
    sk,// "Slovenčina",
    sl,// "Slovenščina",
    sv,// "Svenska",
    tg,// "Тоҷикӣ",
    th,// "ไทย / Phasa Thai",
    tk,// "Туркмен / تركمن ",
    uk,// "Українська",
    uz,// "Ўзбек",
    zh,// "中文",
}
